// <auto-generated />
using System;
using Dinacem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dinacen.Migrations
{
    [DbContext(typeof(AplicacionDbContexto))]
    partial class AplicacionDbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dinacem.Models.BitacoraVehiculo", b =>
                {
                    b.Property<int>("IdBitacoraVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacoraVehiculo"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DistanciaKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRendicion")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoAsignado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TarifaKilometro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdBitacoraVehiculo");

                    b.HasIndex("IdRendicion");

                    b.ToTable("BitacorasVehiculo", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<decimal>("TarifaKilometro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdConfiguracion");

                    b.ToTable("ConfiguracionSistema", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.DevolucionSaldo", b =>
                {
                    b.Property<int>("IdDevolucionSaldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucionSaldo"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRendicion")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroOperacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Voucher")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdDevolucionSaldo");

                    b.HasIndex("IdRendicion")
                        .IsUnique();

                    b.ToTable("DevolucionesSaldo", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.EstadoReembolso", b =>
                {
                    b.Property<int>("IdEstadoReembolso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReembolso"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoReembolso");

                    b.ToTable("EstadoReembolsos", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.EstadoRendicion", b =>
                {
                    b.Property<int>("IdEstadoRendicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoRendicion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoRendicion");

                    b.ToTable("EstadoRendiciones", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.EstadoSolicitud", b =>
                {
                    b.Property<int>("IdEstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoSolicitud"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoSolicitud");

                    b.ToTable("EstadoSolicitudes", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("Comprobante")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DomicilioFiscal")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ExoneracionIGV")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IGV")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdRendicion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoGasto")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Numero")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Serie")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdGasto");

                    b.HasIndex("IdRendicion");

                    b.HasIndex("IdTipoComprobante");

                    b.HasIndex("IdTipoGasto");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Reembolso", b =>
                {
                    b.Property<int>("IdReembolso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReembolso"));

                    b.Property<string>("Banco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComprobantePago")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoReembolso")
                        .HasColumnType("int");

                    b.Property<int>("IdRendicion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdReembolso");

                    b.HasIndex("IdEstadoReembolso");

                    b.HasIndex("IdRendicion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reembolsos", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Rendicion", b =>
                {
                    b.Property<int>("IdRendicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRendicion"));

                    b.Property<string>("ArchivoPdf")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioRevision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoRendicion")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdRendicion");

                    b.HasIndex("IdEstadoRendicion");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("Rendiciones", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RutaComprobante")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Solicitudes", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.TipoComprobante", b =>
                {
                    b.Property<int>("IdTipoComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoComprobante"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoComprobante");

                    b.ToTable("TipoComprobantes", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.TipoGasto", b =>
                {
                    b.Property<int>("IdTipoGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoGasto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoGasto");

                    b.ToTable("TipoGastos", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdZona");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.Zona", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZona"));

                    b.Property<string>("CodigoZona")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("IdZona");

                    b.HasIndex("CodigoZona")
                        .IsUnique();

                    b.ToTable("Zonas", (string)null);
                });

            modelBuilder.Entity("Dinacem.Models.BitacoraVehiculo", b =>
                {
                    b.HasOne("Dinacem.Models.Rendicion", "Rendicion")
                        .WithMany("BitacorasVehiculo")
                        .HasForeignKey("IdRendicion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rendicion");
                });

            modelBuilder.Entity("Dinacem.Models.DevolucionSaldo", b =>
                {
                    b.HasOne("Dinacem.Models.Rendicion", "Rendicion")
                        .WithOne("DevolucionSaldo")
                        .HasForeignKey("Dinacem.Models.DevolucionSaldo", "IdRendicion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rendicion");
                });

            modelBuilder.Entity("Dinacem.Models.Gasto", b =>
                {
                    b.HasOne("Dinacem.Models.Rendicion", "Rendicion")
                        .WithMany("Gastos")
                        .HasForeignKey("IdRendicion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.TipoComprobante", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rendicion");

                    b.Navigation("TipoComprobante");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("Dinacem.Models.Reembolso", b =>
                {
                    b.HasOne("Dinacem.Models.EstadoReembolso", "EstadoReembolso")
                        .WithMany()
                        .HasForeignKey("IdEstadoReembolso")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.Rendicion", "Rendicion")
                        .WithMany()
                        .HasForeignKey("IdRendicion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EstadoReembolso");

                    b.Navigation("Rendicion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dinacem.Models.Rendicion", b =>
                {
                    b.HasOne("Dinacem.Models.EstadoRendicion", "EstadoRendicion")
                        .WithMany()
                        .HasForeignKey("IdEstadoRendicion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.Solicitud", "Solicitud")
                        .WithOne("Rendicion")
                        .HasForeignKey("Dinacem.Models.Rendicion", "IdSolicitud")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EstadoRendicion");

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dinacem.Models.Solicitud", b =>
                {
                    b.HasOne("Dinacem.Models.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany()
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dinacem.Models.Usuario", b =>
                {
                    b.HasOne("Dinacem.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dinacem.Models.Zona", "Zona")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Rol");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Dinacem.Models.Rendicion", b =>
                {
                    b.Navigation("BitacorasVehiculo");

                    b.Navigation("DevolucionSaldo");

                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Dinacem.Models.Solicitud", b =>
                {
                    b.Navigation("Rendicion");
                });

            modelBuilder.Entity("Dinacem.Models.Zona", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
